<?binding.jca DBTrigger_db.jca?>
<wsdl:definitions name="DBTrigger" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/BPMComposer/Project1/DBTrigger" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/BPMComposer/Project1/DBTrigger" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBTrigger">
    <plt:partnerLinkType name="DBTrigger_plt">
        <plt:role name="DBTrigger_role">
            <plt:portType name="tns:DBTrigger_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBTrigger" schemaLocation="xsd/DBTrigger_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="JcTriggerCollection_msg">
        <wsdl:part name="JcTriggerCollection" element="top:JcTriggerCollection"/>
    </wsdl:message>
    <wsdl:portType name="DBTrigger_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:JcTriggerCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
